### ISSUE TITLE
Fixing dependencies of homeassistant-0.104.3

### ISSUE THREAD

**Issue by zen2** [onkelbeh/HomeAssistantRepository#9] opened 2020-01-31 10:55 UTC
Hello and thanks for the big work involved in this overlay.
I'm currently migrating my HA from a rpi3 to a x86 64 bits box.

As I need 'harmony' USE flag for HA, portage complain about a new dependency that have appeared in last dev-python/aioharmony-0.1.13:

```
!!! The ebuild selected to satisfy ">=dev-python/slixmpp-1.4.2" has unmet requirements.
- dev-python/slixmpp-1.4.2::HomeAssistantRepository USE="-test" PYTHON_TARGETS="-python3_6"

  The following REQUIRED_USE flag constraints are unsatisfied:
    python_targets_python3_6

  The above constraints are a subset of the following complete expression:
    any-of ( python_targets_python3_6 )

(dependency required by "dev-python/aioharmony-0.1.13::HomeAssistantRepository" [ebuild])
(dependency required by "app-misc/homeassistant-9999::HomeAssistantRepository[harmony]" [ebuild])
(dependency required by "homeassistant" [argument])

```

**Comment by onkelbeh** [comment] 2020-02-01 10:12
Hi,

it's a pleasure that you find it useful.

Funny, because [I just began](https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/11) adding KEYWORDS="~arm64" to the ebuilds, so Home Assistant could be run with [Gentoo on Raspberry](https://github.com/sakaki-/gentoo-on-rpi-64bit) in the near future. But CPU can always be replaced with more CPU :-)

Just added a [patched ebuild](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/804ad959f1bf628be9a2c7d76e176dd332caec71), this should let you compile it now.
Cannot test, no Harmony here, but it compiles now.

I was adding many (missing) upstream dependencies in the last weeks. Surely many packages list [requirements](https://github.com/ehendrix23/aioharmony/blob/master/setup.py) which aren't used/needed anyway.

Please close the ticket as soon as it works.

Have fun.
 \B.

**Comment by zen2** [comment] 2020-02-01 10:54
I think there is another problem:
```

emerge: there are no ebuilds to satisfy "~dev-python/importlib_metadata-1.3.0[python_targets_python3_7(-)?,python_targets_python3_8(-)?,-python_single_target_python3_7(-),-python_single_target_python3_8(-)]".
(dependency required by "app-misc/homeassistant-0.104.2::HomeAssistantRepository" [ebuild])
(dependency required by "homeassistant" [argument])
```
because of no 1.3.0 version anymore:
```
[I] dev-python/importlib_metadata
     Available versions:  0.23-r1^t 1.4.0^t ~1.5.0^t {doc test PYTHON_TARGETS="pypy3 python2_7 python3_6 python3_7 python3_8"}
```

Note that I got my system in ~amd64 (unstable) because from my experience it's more easy to maintain a full unstable system that an stable one with a bunch of unstable ebuild.

**Comment by zen2** [comment] 2020-02-01 11:34
It seems that I've solved portage dependencies with these modifications:

```
--- homeassistant-0.104.3.ebuild	2020-02-01 12:14:45.272402083 +0100
+++ homeassistant-0.104.3-r1.ebuild	2020-02-01 12:27:36.732547560 +0100
@@ -44,7 +44,7 @@
 	>=dev-python/cdu-0.1.3[${PYTHON_USEDEP}]
 	>=dev-python/certifi-2019.11.28[${PYTHON_USEDEP}]
 	$(python_gen_cond_dep '~dev-python/contextvars-2.4[${PYTHON_USEDEP}]' python3_6)
-	~dev-python/cffi-1.12.2[${PYTHON_USEDEP}]
+	>=dev-python/cffi-1.12.2[${PYTHON_USEDEP}]
 	>=dev-python/chardet-3.0.4[${PYTHON_USEDEP}]
 	~dev-python/colorlog-4.0.2[${PYTHON_USEDEP}]
 	>=dev-python/coverage-4.5.2[${PYTHON_USEDEP}]
@@ -61,7 +61,7 @@
 	>=dev-python/idna-ssl-1.1.0[${PYTHON_USEDEP}]
 	>=dev-python/ifaddr-0.1.6[${PYTHON_USEDEP}]
 	>=dev-python/immutables-0.9[${PYTHON_USEDEP}]
-	~dev-python/importlib_metadata-1.3.0[${PYTHON_USEDEP}]
+	>=dev-python/importlib_metadata-1.3.0[${PYTHON_USEDEP}]
 	>=dev-python/jinja-2.10.3[${PYTHON_USEDEP}]
 	>=dev-python/jmespath-0.9.4[${PYTHON_USEDEP}]
 	>=dev-python/jose-1.0.0[${PYTHON_USEDEP}]
@@ -215,7 +215,7 @@
 	z-wave? ( ~dev-python/pynacl-1.3.0[${PYTHON_USEDEP}]
 			  ~dev-python/homeassistant-pyozw-0.1.7[${PYTHON_USEDEP}]
 			  ~dev-python/pydispatcher-2.0.5[${PYTHON_USEDEP}]
-			  ~dev-python/cffi-1.12.2[${PYTHON_USEDEP}] )
+			  >=dev-python/cffi-1.12.2[${PYTHON_USEDEP}] )
 "
 
 DEPEND="${RDEPEND}
```

Now emerge is going on... 

Note: It's not possible to use "webostv" USE flag because dev-python/aiopylgtv need dev-python/asyncio that doesn't exist at all in portage or in this overlay.

**Comment by zen2** [comment] 2020-02-01 13:18
dev-python/ruamel-yaml can't be downloaded anymore from bitbucket but can be found here:
https://sourceforge.net/projects/ruamel-yaml/

**Comment by zen2** [comment] 2020-02-01 14:56
**Problem:**  USE flag "webostv" can't be used because dev-python/aiopylgtv need dev-python/asyncio that doesn't exist at all in portage or in overlay.

**Comment by onkelbeh** [comment] 2020-02-01 23:26
OK, a lot of stuff. Thanks for your feedback.

All 5 issues should be fixed in
* [harmony](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/81ce810208a5939e736e0157c6afa40378769d51), as above.
* [importlib_metadata](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/17cd3936ff1a3d43bb580cf5eef22c0bc696179f), added a copy to the repo.
* [cffi](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/e2cfc3f27fa8b3c0e62cfa304ff271edffbcf59a) and [cffi 4 HA 0.105.0beta3](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/2c58262511c818ec3164a4c8646297d2a2d3173d), imho cffi isn't needed anymore, at least it disappeared from current requirements.txt, will check this out tomorrow.
* [ruamel-yaml](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/9f270719a62b93f210a80b3a295c770b7c33f835), sources now from pypi.
* [asyncio](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/49f4261747b1f7add88560feeebad84196f29649), Python 3.7 imho has it's own lib.

**Comment by onkelbeh** [comment] 2020-02-01 23:46
Uh, just saw your first post again closing my windows: `python_targets_python3_6`
Make sure you are installing on Python 3.7, [support for 3.6 was dropped](https://github.com/home-assistant/home-assistant/pull/27680) with 0.103.0

**Comment by zen2** [comment] 2020-02-02 14:55
> Uh, just saw your first post again closing my windows: `python_targets_python3_6`
> Make sure you are installing on Python 3.7, [support for 3.6 was dropped](https://github.com/home-assistant/home-assistant/pull/27680) with 0.103.0

I got only python 3.7 installed but portage wanted python 3.6 to respect slixmpp-1.4.2.ebuild.

**Comment by zen2** [comment] 2020-02-02 15:20
It seems you need to recreate manifest for dev-python/ruamel-yaml :
```
!!! Digest verification failed:
!!! /var/lib/layman/HomeAssistantRepository/dev-python/ruamel-yaml/ruamel-yaml-0.15.89.ebuild
!!! Reason: Filesize does not match recorded size
!!! Got: 1111
!!! Expected: 1108
```

**Comment by onkelbeh** [comment] 2020-02-03 07:45
OK, will check out slixmpp-1.4.2 soon.

ruamel-yaml is fixed with https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/fa8509f068a424e4bf74a5661cfeb4da3720c673. Had a heavy power outage this weekend caused by a storm. Seems I forgot to do the Manifest before pushing with my last battery power.

There are still 2 dependency issues left:
  * dev-python/python-dateutil
  * trying to remove cffi

I'll try to clean this up before 0.105.0 and will do a fresh complete compile test as soon as 0.105.0 is out.

Could you also take a look if your `/etc/homeassistant/deps` is empty?

**Comment by onkelbeh** [comment] 2020-02-03 20:59
**slixmpp-1.4.2:**
On my box, all related components for aioharmony compile fine:

```
root@g18-hass:/usr/portage/homeassistant/dev-python # emerge -1tav dev-python/aioharmony --autounmask=y

Local copy of remote index is up-to-date and will be used.

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


Local copy of remote index is up-to-date and will be used.

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N    ~] dev-python/aioharmony-0.1.13-r1::HomeAssistantRepository  USE="-test" PYTHON_TARGETS="python3_7 -python3_8" 26 KiB
[ebuild  N    ~]  dev-python/slixmpp-1.4.2-r1::HomeAssistantRepository  USE="-test" PYTHON_TARGETS="python3_7 -python3_8" 0 KiB
[ebuild  N     ]   net-dns/libidn-1.35:0/12::gentoo  USE="nls -doc -emacs -java -mono -static-libs" 0 KiB
[ebuild  N    ~]   dev-python/aiodns-2.0.0-r1::gentoo  PYTHON_TARGETS="python3_7 -python3_6" 0 KiB
[ebuild  N    ~]    dev-python/pycares-3.1.1::gentoo  PYTHON_TARGETS="python3_7 -python3_6 -python3_8" 0 KiB
[ebuild  N     ]     virtual/python-cffi-0::gentoo  PYTHON_TARGETS="python3_7 (-pypy3) -python2_7 -python3_6 (-python3_8)" 0 KiB

Total: 6 packages (6 new), Size of downloads: 26 KiB

Would you like to merge these packages? [Yes/No]
>>> Verifying ebuild manifests
>>> Emerging (1 of 6) virtual/python-cffi-0::gentoo
>>> Emerging (2 of 6) net-dns/libidn-1.35::gentoo
>>> Installing (1 of 6) virtual/python-cffi-0::gentoo
>>> Emerging (3 of 6) dev-python/pycares-3.1.1::gentoo
>>> Installing (3 of 6) dev-python/pycares-3.1.1::gentoo
>>> Emerging (4 of 6) dev-python/aiodns-2.0.0-r1::gentoo
>>> Installing (4 of 6) dev-python/aiodns-2.0.0-r1::gentoo
>>> Installing (2 of 6) net-dns/libidn-1.35::gentoo
>>> Emerging (5 of 6) dev-python/slixmpp-1.4.2-r1::HomeAssistantRepository
>>> Installing (5 of 6) dev-python/slixmpp-1.4.2-r1::HomeAssistantRepository
>>> Emerging (6 of 6) dev-python/aioharmony-0.1.13-r1::HomeAssistantRepository
>>> Installing (6 of 6) dev-python/aioharmony-0.1.13-r1::HomeAssistantRepository
>>> Jobs: 6 of 6 complete                           Load avg: 2.14, 1.48, 1.25
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * Regenerating GNU info directory index...
 * Processed 96 info files.

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

-> Searching for services that need to be restarted ... done
=> Found 0 services that need to be restarted or reloaded
No known services need to be restarted.
=> Found 0 inittab processes that need to be restarted
root@g18-hass:/usr/portage/homeassistant/dev-python # eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.7
  [2]   python2.7
  [3]   python3.8 (fallback)
root@g18-hass:/usr/portage/homeassistant/dev-python #
```

**Comment by onkelbeh** [comment] 2020-02-03 21:22
**python-dateutil:**
`python-dateutil-2.8.0` was erroneously required by `botocore-1.12.252`.

Adjusted this according to the [1.12.252 setup.py](https://github.com/boto/botocore/blob/1.12.252/setup.py) in [botocore-1.12.252-r1](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/99972d071abc77552967fc448d78c67170e26b36).

Now `python-dateutil-2.8.1-r1` is allowed.

**Closed** 2020-02-06 16:45 UTC
Labels: bug
